<?php

/**
 * Placeholder only — this file is committed to git and must NEVER contain
 * a real secret.
 *
 * Required secret format (enforced by relay.php AND mailer.ts — both
 * reject anything else, including this placeholder, before ever comparing
 * it against a submitted token):
 *   - exactly 64 lowercase hexadecimal characters
 *   - regex: \A[a-f0-9]{64}\z
 *   - i.e. a 32-byte / 256-bit secret generated with:
 *       openssl rand -hex 32
 *
 * The placeholder value below is deliberately NOT in that format (it's not
 * hex, and it's not 64 characters) — relay.php's validator rejects it
 * explicitly by name in addition to rejecting it on format alone, so a
 * forgotten copy-without-editing of this file can never become a working
 * credential.
 *
 * To deploy:
 *   1. Copy this file to the Zone account root (the directory that
 *      contains htdocs/, logs/, phpini/, stats/ — NOT inside htdocs/)
 *      and rename it to exactly:
 *        mail-relay-secret.php
 *   2. Replace the placeholder value below with a real secret generated by:
 *        openssl rand -hex 32
 *      Never paste the generated value into chat, a screenshot, a log
 *      line, a support ticket, or any other channel outside this one file
 *      and the matching Render environment variable.
 *   3. Set the SAME value as MAIL_RELAY_SECRET in Render's environment
 *      configuration for the api-server service.
 *   4. Never commit the real mail-relay-secret.php file — it must only
 *      ever exist on the Zone account's filesystem, outside htdocs/, and
 *      as the MAIL_RELAY_SECRET value in Render's environment config.
 *
 * relay.php loads this file via:
 *   dirname(__DIR__, 2) . '/mail-relay-secret.php'
 * (htdocs/mail-relay/relay.php -> htdocs/ -> account root), and fails
 * closed with a generic 500 if the file is missing, malformed, or the
 * secret inside it doesn't match the required format above.
 */

return [
    'secret' => 'REPLACE_WITH_A_REAL_HIGH_ENTROPY_SECRET',
];
